// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

type Storage_Expecter struct {
	mock *mock.Mock
}

func (_m *Storage) EXPECT() *Storage_Expecter {
	return &Storage_Expecter{mock: &_m.Mock}
}

// GetSlice provides a mock function with given fields: ctx
func (_m *Storage) GetSlice(ctx context.Context) ([]int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSlice")
	}

	var r0 []int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []int); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_GetSlice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSlice'
type Storage_GetSlice_Call struct {
	*mock.Call
}

// GetSlice is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Storage_Expecter) GetSlice(ctx interface{}) *Storage_GetSlice_Call {
	return &Storage_GetSlice_Call{Call: _e.mock.On("GetSlice", ctx)}
}

func (_c *Storage_GetSlice_Call) Run(run func(ctx context.Context)) *Storage_GetSlice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Storage_GetSlice_Call) Return(numbers []int, err error) *Storage_GetSlice_Call {
	_c.Call.Return(numbers, err)
	return _c
}

func (_c *Storage_GetSlice_Call) RunAndReturn(run func(context.Context) ([]int, error)) *Storage_GetSlice_Call {
	_c.Call.Return(run)
	return _c
}

// PutNumber provides a mock function with given fields: ctx, num
func (_m *Storage) PutNumber(ctx context.Context, num int) error {
	ret := _m.Called(ctx, num)

	if len(ret) == 0 {
		panic("no return value specified for PutNumber")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, num)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_PutNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutNumber'
type Storage_PutNumber_Call struct {
	*mock.Call
}

// PutNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - num int
func (_e *Storage_Expecter) PutNumber(ctx interface{}, num interface{}) *Storage_PutNumber_Call {
	return &Storage_PutNumber_Call{Call: _e.mock.On("PutNumber", ctx, num)}
}

func (_c *Storage_PutNumber_Call) Run(run func(ctx context.Context, num int)) *Storage_PutNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *Storage_PutNumber_Call) Return(_a0 error) *Storage_PutNumber_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_PutNumber_Call) RunAndReturn(run func(context.Context, int) error) *Storage_PutNumber_Call {
	_c.Call.Return(run)
	return _c
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
