// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUseCase is an autogenerated mock type for the UseCase type
type MockUseCase struct {
	mock.Mock
}

type MockUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUseCase) EXPECT() *MockUseCase_Expecter {
	return &MockUseCase_Expecter{mock: &_m.Mock}
}

// GetSlices provides a mock function with given fields: ctx
func (_m *MockUseCase) GetSlices(ctx context.Context) ([]int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSlices")
	}

	var r0 []int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []int); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUseCase_GetSlices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSlices'
type MockUseCase_GetSlices_Call struct {
	*mock.Call
}

// GetSlices is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUseCase_Expecter) GetSlices(ctx interface{}) *MockUseCase_GetSlices_Call {
	return &MockUseCase_GetSlices_Call{Call: _e.mock.On("GetSlices", ctx)}
}

func (_c *MockUseCase_GetSlices_Call) Run(run func(ctx context.Context)) *MockUseCase_GetSlices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUseCase_GetSlices_Call) Return(_a0 []int, _a1 error) *MockUseCase_GetSlices_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUseCase_GetSlices_Call) RunAndReturn(run func(context.Context) ([]int, error)) *MockUseCase_GetSlices_Call {
	_c.Call.Return(run)
	return _c
}

// PutNumber provides a mock function with given fields: ctx, num
func (_m *MockUseCase) PutNumber(ctx context.Context, num int) error {
	ret := _m.Called(ctx, num)

	if len(ret) == 0 {
		panic("no return value specified for PutNumber")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, num)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUseCase_PutNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutNumber'
type MockUseCase_PutNumber_Call struct {
	*mock.Call
}

// PutNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - num int
func (_e *MockUseCase_Expecter) PutNumber(ctx interface{}, num interface{}) *MockUseCase_PutNumber_Call {
	return &MockUseCase_PutNumber_Call{Call: _e.mock.On("PutNumber", ctx, num)}
}

func (_c *MockUseCase_PutNumber_Call) Run(run func(ctx context.Context, num int)) *MockUseCase_PutNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockUseCase_PutNumber_Call) Return(_a0 error) *MockUseCase_PutNumber_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUseCase_PutNumber_Call) RunAndReturn(run func(context.Context, int) error) *MockUseCase_PutNumber_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUseCase creates a new instance of MockUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUseCase {
	mock := &MockUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
